theme: fluid
language: zh-CN

title: 'Potat0 Box'
subtitle: '世界那么大 我想去看看'
description: 'Just a box for Potat0.'
author: Potat0
SEOTitle: 'Potat0 Box'
default_layout: post
new_post_name: :year-:month-:day-:title.md
permalink: posts/:year:month:day/:title/
post_asset_folder: true
url: 'https://potat0.cc/'

markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-cjk-breaks
    - markdown-it-container
    - markdown-it-emoji
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-mark
    - markdown-it-pangu
    - markdown-it-sub
    - markdown-it-sup
    - markdown-it-table-of-contents
    - markdown-it-task-lists

html_minifier:
  enable: true
  ignore_error: false
  silent: false
css_minifier:
  enable: true
  silent: false
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  silent: false
  exclude:
    - '*.min.js'
image_minifier:
  enable: true
  interlaced: true
  multipass: true
  optimizationLevel: 2
  pngquant: true
  progressive: true
  silent: false

sitemap:
  path: sitemap.xml
  rel: true
  tags: true
  categories: false

nofollow:
  enable: true
  field: site

feed:
  enable: true
  type: atom
  autodiscovery: true
  content: true
  hub: https://pubsubhubbub.appspot.com
  icon: /favicon.ico
  limit: 20
  order_by: -date
  template: ./atom_template.xml
