name: Auto build blog
on:
  push:
    branches:
      - master
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '14.x'
    - name: Check out code
      uses: actions/checkout@main
    - name: Fetch Posts
      run: |
        git clone https://${{secrets.UPLOAD_TOKEN}}@github.com/Potat0000/Blog-Posts.git source/_posts
        rm -rf source/_posts/.git*
    - name: Install NPM packages
      run: |
        npm install -g hexo-cli
        npm install
    - name: Patch
      run: |
        find ./source/lib/ -type f -exec sed -i '1i\{% raw %}' {} \;
        find ./source/lib/ -type f -exec sed -i '$a\{% endraw %}' {} \;
        cd ./node_modules/hexo-theme-fluid/
        patch -p1 < ../../patch/FooterLayout.patch
        cd layout
        patch -p1 < ../../../patch/Accessibility.patch
        cd _partial
        patch head.ejs < ../../../../patch/OpenGraph.patch
    - name: Build
      env:
        UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      run: |
        hexo g
        sed -i 's`IEJUMPIEJUMPIEJUMP`if(/*@cc_on!@*/false||(!!window.MSInputMethodContext\&\&!!document.documentMode))window.location.href="https://support.dmeng.net/upgrade-your-browser.html?referrer="+encodeURIComponent(window.location.href);`g' `grep IEJUMPIEJUMPIEJUMP -rl ./public`
    - name: Clean up
      run: |
        cd public
        rm -rf xml
        rm img/avatar.png img/default.png img/favicon.png
    - name: Deploy to Aliyun OSS
      run: |
        sed -i 's`OSSTOKENOSSTOKENOSSTOKEN`${{secrets.OSS_TOKEN}}`g' _config.yml
        hexo d
