name: Auto build blog
on:
  push:
    branches:
      - master
  repository_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '14.x'
    - name: Check out code
      uses: actions/checkout@main
    - name: Fetch Posts
      run: |
        git clone https://${{secrets.UPLOAD_TOKEN}}@github.com/Potat0000/Blog-Posts.git source/_posts
        rm -rf source/_posts/.git*
    - name: Install NPM packages
      run: |
        npm install -g hexo-cli
        npm install
    - name: Patch
      run: |
        sed -i 's`maximum-scale=1.0, user-scalable=no`maximum-scale=5.0`g' `find . -name "head.ejs"`
        sed -i 's`data-target="#modalSearch"`data-target="#modalSearch" aria-label="Search"`g' `find . -name "nav.ejs"`
        sed -i 's`<a class="nav-link" target="_self">`<a class="nav-link" target="_self" aria-label="Color Toggle">`g' `find . -name "nav.ejs"`
        sed -i 's`target="_self"`target="_self" href="javascript:;"`g' `find . -name "nav.ejs"`
        sed -i 's`id="scroll-top-button"`id="scroll-top-button" aria-label="TOP"`g' `find . -name "layout.ejs"`
    - name: Config Git
      run: |
        git config --global user.name "Actions"
        git config --global user.email "actions@github.com"
    - name: Build
      env:
        UPLOAD_TOKEN: ${{ secrets.UPLOAD_TOKEN }}
      run: |
        hexo g
        sed -i 's`IEJUMPIEJUMPIEJUMP`if(/*@cc_on!@*/false||(!!window.MSInputMethodContext\&\&!!document.documentMode))window.location.href="https://support.dmeng.net/upgrade-your-browser.html?referrer="+encodeURIComponent(window.location.href);`g' `grep IEJUMPIEJUMPIEJUMP -rl ./public`
    - name: Clean up
      run: |
        cd public
        rm -rf xml
        rm img/avatar.png img/default.png img/favicon.png
    - name: Deploy to Aliyun OSS
      run: |
        sed -i 's`OSSTOKENOSSTOKENOSSTOKEN`${{secrets.OSS_TOKEN}}`g' _config.yml
        hexo d
