name: Auto build blog
on:
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@main
      with:
        node-version: '14.x'
    - uses: actions/setup-python@main
      with:
        python-version: '3.x'
    - name: Check out code
      uses: actions/checkout@main
    - name: Fetch Theme and Posts
      run: |
        git clone https://${{secrets.POST_CHECKOUT_TOKEN}}@github.com/Potat0000/Blog-Theme.git themes/fluid
        git clone https://${{secrets.POST_CHECKOUT_TOKEN}}@github.com/Potat0000/Blog-Posts.git source/_posts
        python3 build_script/gen_updatedtime.py
        rm -rf source/_posts/.git*
    - name: Install packages
      run: |
        npm install -g hexo-cli
        npm install
        pip3 install aliyun-python-sdk-cdn aliyun-python-sdk-core
    - name: Get and Patch Lib Files
      run: |
        cp source/img/icon/favicon.ico source/
        bash build_script/get_libs.sh
    - name: Build
      run: |
        hexo g
        sed -i 's`IEJUMPIEJUMPIEJUMP`if(/*@cc_on!@*/false||(!!window.MSInputMethodContext\&\&!!document.documentMode))window.location.href="https://support.dmeng.net/upgrade-your-browser.html?referrer="+encodeURIComponent(window.location.href);`g' `grep IEJUMPIEJUMPIEJUMP -rl ./public`
    - name: Clean up
      run: |
        cd public
        rm -rf xml
        rm img/avatar.png img/default.png img/favicon.png
    - name: Deploy to Aliyun OSS
      run: |
        sed -i 's`ALIYUN_ACCESSKEY_ID`${{secrets.ALIYUN_ACCESSKEY_ID}}`g' _config.yml
        sed -i 's`ALIYUN_ACCESSKEY_SECRET`${{secrets.ALIYUN_ACCESSKEY_SECRET}}`g' _config.yml
        hexo d
    - name: Refresh CDN
      run: |
        echo "https://potat0.cc/" > refresh.txt
        python3 build_script/Refresh.py -i ${{secrets.ALIYUN_ACCESSKEY_ID}} -k ${{secrets.ALIYUN_ACCESSKEY_SECRET}} -r refresh.txt -t clear -o Directory
        echo -ne "https://potat0.cc/index.html\nhttps://potat0.cc/atom.xml\nhttps://potat0.cc/css/main.css\nhttps://potat0.cc/service-worker.js\nhttps://potat0.cc/service-worker.js.map\nhttps://potat0.cc/" > refresh.txt
        ls public/workbox-*.js | cut -d "/" -f 2 >> refresh.txt
        echo -n "https://potat0.cc/" >> refresh.txt
        ls public/workbox-*.js.map | cut -d "/" -f 2 >> refresh.txt
        python3 build_script/Refresh.py -i ${{secrets.ALIYUN_ACCESSKEY_ID}} -k ${{secrets.ALIYUN_ACCESSKEY_SECRET}} -r refresh.txt -t push
        curl -H "Content-Type: application/x-www-form-urlencoded" -X POST "https://pubsubhubbub.appspot.com/publish?hub.mode=publish&hub.url=https://potat0.cc/atom.xml"
